name: Rezilion Test GitHub Action
on: [push]
jobs:
  rezilion-scan:
    runs-on: ubuntu-latest
    container:
      image: dtwitch/node-test
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_RUN_REMEDIATE: true
      REZILION_API_KEY: ${{ secrets.REZILION_API_KEY }}
      REZILION_BRANCH_NAME_UPLOADING_REGEX: ^main$
 
    steps:
      - uses: Rezilion/github-action@v2.8.0 
        with:
          image_name: 'dtwitch/node-test'
          mode: 'start'
          command: |
            timeout 10 node-test || true
      
  rezilion-validate:
    needs: [rezilion-scan]
    runs-on: ubuntu-latest
    container:
      image: dtwitch/node-test
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}
      REZILION_RUN_REMEDIATE: true
    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.8.0
        with:
          mode: 'validate'
