name: Rezilion Test GitHub Action
on: [push]
jobs:
  rezilion-scan:
    runs-on: ubuntu-latest
    container:
      image: dtwitch/node-test
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}
 
    steps:
      - uses: Rezilion/github-action@v2.9.0 
        with:
          image_name: 'dtwitch/node-test'
          mode: 'start'
          command: sleep 5
      
  rezilion-validate:
    needs: [rezilion-scan]
    runs-on: ubuntu-latest
    container:
      image: dtwitch/node-test
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_API_KEY: ${{ secrets.REZILION_API_KEY }}
      REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}
      REZILION_BRANCH_NAME_UPLOADING_REGEX: ^main$
      REZILION_RUN_REMEDIATE: true
    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.9.0
        with:
          mode: 'validate'

  deploy-centos-staging:
    needs: [rezilion-scan, rezilion-validate]
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: connect and run script
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "/home/centos/refresh_nodetest.sh && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
